# Generated by Django 3.2.6 on 2021-09-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imageFun',
            new_name='image',
        ),
    ]
